# Generated by Django 5.2.1 on 2025-05-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_inventorylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='operation',
            field=models.CharField(choices=[('add', 'Добавление'), ('remove', 'Списание'), ('update', 'Обновление')], max_length=10),
        ),
    ]
